project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4
    code-tools: true
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    highlight-style: arrow
    grid:
      sidebar-width: 180px
      body-width: 980px
      margin-width: 300px
      gutter-width: 1.0rem

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
  sidebar:
    style: floating

metadata-files: [nbdev.yml, sidebar.yml]