# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/trufl',
                'doc_host': 'https://franckalbinet.github.io',
                'git_url': 'https://github.com/franckalbinet/trufl',
                'lib_path': 'trufl'},
  'syms': { 'trufl.loading': {'trufl.loading.foo': ('optimizer.html#foo', 'trufl/loading.py')},
            'trufl.optimizer': {'trufl.optimizer.foo': ('optimizer.html#foo', 'trufl/optimizer.py')},
            'trufl.reader': { 'trufl.reader.read_geojson': ('reader.html#read_geojson', 'trufl/reader.py'),
                              'trufl.reader.read_shapefile': ('reader.html#read_shapefile', 'trufl/reader.py')},
            'trufl.sampler': { 'trufl.sampler.Sampler': ('sampler.html#sampler', 'trufl/sampler.py'),
                               'trufl.sampler.Sampler.__init__': ('sampler.html#sampler.__init__', 'trufl/sampler.py'),
                               'trufl.sampler.Sampler.sample': ('sampler.html#sampler.sample', 'trufl/sampler.py'),
                               'trufl.sampler.Sampler.to_geodataframe': ('sampler.html#sampler.to_geodataframe', 'trufl/sampler.py')},
            'trufl.utils': { 'trufl.utils.anonymize_raster': ('utils.html#anonymize_raster', 'trufl/utils.py'),
                             'trufl.utils.gridder': ('utils.html#gridder', 'trufl/utils.py'),
                             'trufl.utils.reproject_raster': ('utils.html#reproject_raster', 'trufl/utils.py')}}}
