# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/trufl',
                'doc_host': 'https://franckalbinet.github.io',
                'git_url': 'https://github.com/franckalbinet/trufl',
                'lib_path': 'trufl'},
  'syms': {'trufl.core': {'trufl.core.foo': ('core.html#foo', 'trufl/core.py')}}}
