"""Rank locations by sampling priority from their state variables, using multiple-criteria decision-making.

Docs: https://franckalbinet.github.io/trufl/optimizer.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_optimizer.ipynb.

# %% auto #0
__all__ = ['Optimizer']

# %% ../nbs/02_optimizer.ipynb #19e6f5fa
import numpy as np
import pandas as pd
from fastcore.basics import patch
from .mcdm import score, normalize, weigh

# %% ../nbs/02_optimizer.ipynb #c55023ff
class Optimizer:
    "Rank locations by sampling priority from their state variables."
    def __init__(self,
        state:pd.DataFrame, # One row per `loc_id` and one column per criterion, as returned by calling a `State`
    ):
        self.state = state
        
        self.matrix = state.to_numpy()
        return

# %% ../nbs/02_optimizer.ipynb #9d6313f3
@patch
def get_rank(self:Optimizer,
    is_benefit_x:list, # One flag per criterion: `True` if a high value raises sampling priority (benefit), `False` if a low value does (cost)
    w_vector:list=None, # Weight of each criterion, summing to 1; computed with `w_method` if `None`
    n_method:str=None, # Normalization method: `LINEAR1`, `LINEAR2`, `LINEAR3` or `VECTOR`; `None` requires values already in [0, 1]
    c_method:str=None, # Correlation method for `CRITIC` and `VIC` weighting: `PEARSON`, `ABSPEARSON` or `DCOR`
    w_method:str=None, # Weighting method used when `w_vector` is `None`: `MW`, `EM`, `SD`, `CRITIC` or `VIC`
    s_method:str=None, # Scoring method: `CP` or `TOPSIS`. Required
) -> pd.DataFrame: # A `rank` column indexed by `loc_id`, sorted from highest priority (rank 1) to lowest
    "Rank each location in `state` by sampling priority."
    # normailize the matrix
    z_matrix, is_benefit_z = normalize(self.matrix, is_benefit_x, n_method)
    
     # replace nan values with 0 if cost and & 1 if benefit
    for i, is_benefit in enumerate(is_benefit_z):
        if is_benefit:
            z_matrix[:, i][np.isnan(z_matrix[:, i])] = 1
        else:
            z_matrix[:, i][np.isnan(z_matrix[:, i])] = 0

    if w_vector is None:
            # Weigh each criterion using the selected methods
            w_vector = weigh(z_matrix, w_method, c_method)
    else:
        pass

    s_vector, desc_order = score(z_matrix, is_benefit_z, w_vector, s_method)
    state = self.state.copy()
    state['value'] = s_vector
    df = state[['value']]

    # Get the indices of the sorted scores
    if desc_order:
        df_sorted = df.sort_values(by='value', ascending=False)
    else:
        df_sorted = df.sort_values(by='value', ascending=True)
    
    df_sorted['rank'] = range(1, len(df_sorted) + 1)
    df_rank = df_sorted[['rank']]
    
    return df_rank
