"""Fill in a module description here

Docs: https://franckalbinet.github.io/trufl/reader.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_reader.ipynb.

# %% auto #0
__all__ = ['read_shapefile', 'read_geojson']

# %% ../nbs/00_reader.ipynb #fb96ddb5
def read_shapefile(shp):
    # return geopandas
    pass

# %% ../nbs/00_reader.ipynb #1b49ac2e
def read_geojson(shp):
    # return geopandas
    pass
