"""Read administrative units and field measurements from vector files. The readers are placeholders and are not implemented yet.

Docs: https://franckalbinet.github.io/trufl/reader.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_reader.ipynb.

# %% auto #0
__all__ = ['read_shapefile', 'read_geojson']

# %% ../nbs/00_reader.ipynb #fb96ddb5
def read_shapefile(
    shp:str, # Path to the shapefile
):
    "Read `shp` into a `GeoDataFrame`. Not implemented yet."

# %% ../nbs/00_reader.ipynb #1b49ac2e
def read_geojson(
    shp:str, # Path to the GeoJSON file
):
    "Read `shp` into a `GeoDataFrame`. Not implemented yet."
