"""Draw random sample locations inside areas, and split a sampling budget across areas by priority rank.

Docs: https://franckalbinet.github.io/trufl/sampler.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_sampler.ipynb.

# %% auto #0
__all__ = ['Sampler', 'rank_to_sample']

# %% ../nbs/01_sampler.ipynb #000667b9
import rasterio
import fastcore.all as fc
import geopandas as gpd
import pandas as pd
import numpy as np

# %% ../nbs/01_sampler.ipynb #31312993
class Sampler:
    "Draw random sample locations inside the areas of `smp_areas`."
    def __init__(self,
        smp_areas:gpd.GeoDataFrame, # Areas to sample from, such as the output of `gridder`, indexed by `loc_id`
    ):
        fc.store_attr()
        
    @property
    def loc_ids(self):
        "Unique `loc_id` values of `smp_areas`. Raises `ValueError` if any value repeats."
        arr = self.smp_areas.reset_index().loc_id.values
        if len(arr) != len(np.unique(arr)):
            raise ValueError('`loc_id` column contains non-unique values.')
        else:
            return arr
        
    def sample(self,
        n:np.ndarray, # Number of points to draw in each area, in `smp_areas` order
        **kwargs # Passed to `GeoSeries.sample_points`, such as `method` or `rng`
    ) -> gpd.GeoDataFrame: # One `MultiPoint` per area, indexed by `loc_id`. Areas with `n` of 0 are left out
        "Draw `n` random points inside each area."
        mask = n == 0    
        pts_gseries = self.smp_areas[~mask].sample_points(n[~mask], **kwargs)
        gdf_pts = gpd.GeoDataFrame(geometry=pts_gseries, index=pts_gseries.index)
        gdf_pts.index.name = 'loc_id'
        return gdf_pts

# %% ../nbs/01_sampler.ipynb #f5336728
def rank_to_sample(
    ranks:np.ndarray, # Rank of each area, in `loc_id` order. Rank 1 is the highest priority
    budget:int, # Total number of samples to allocate
    min:int=0, # Minimum number of samples per area
    policy:str="Weighted", # Allocation policy: `Weighted` or `quantiles`
) -> np.ndarray: # Number of samples for each area, in the order of `ranks`
    "Split `budget` samples across areas according to their `ranks`."
    if policy == "Weighted":
        weights = 1/ranks
        normalized_weights = np.array(weights) / np.sum(weights)
        allocation = np.round(budget * normalized_weights).astype(int)
        return np.where(allocation < min, min, allocation)
    
    elif policy == "quantiles":
        # 4. Sampling policy (based on 4 quantiles of rank)
        n_quantile = len(ranks)/4
        sampling_policy = [int(budget*0.5/n_quantile), int(budget*0.3/n_quantile), int(budget*0.20/n_quantile), 0]

        # Calculate quantiles thresholds
        quantiles_thresholds = np.quantile(ranks, [0.25, 0.5, 0.75, 1.0])
        
        # Assign each rank to a quantile
        quantile_indices = np.digitize(ranks, quantiles_thresholds, right=True)
        
        # Map each quantile to its corresponding value in sampling_policy
        samples_per_quantile = np.array([sampling_policy[i] for i in quantile_indices])
        
        # Ensure minimum samples collected per area
        samples_per_quantile = np.where(samples_per_quantile < min, min, samples_per_quantile)
        
        return samples_per_quantile
    else:
        raise ValueError(f'Policy {policy} not implemented.')
